name: build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu', 'windows', 'macos']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get python
        uses: actions/setup-python@v2
      - name: get conan
        uses: turtlebrowser/get-conan@main
      - name: cache conan
        uses: actions/cache@v2
        with:
           path: ~/.conan
           key: ${{ matrix.os }}-conan-3
      - name: build
        run: ./ci/ci.bash
        shell: bash
      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: work/install
  
  package:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download all build artifacts
        uses: actions/download-artifact@v2
        with:
          path: work/artifacts
      - name: build
        run: sh ci/package.bash work/artifacts
        shell: bash
      - name: commit
        run: |
          git config --global user.name 'samsface'
          git config --global user.email 'samsface@users.noreply.github.com'
          git add -A
          git commit -am "automated commit"
          git push

  remove-old-artifacts:
    needs: [package]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: remove-old-artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '10 minutes'
